name: CI/CD for Spring Boot with Docker and OCI

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '21'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Get short SHA
      id: vars
      run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64, amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Oracle Container Registry
      run: echo ${{ secrets.OCI_REGISTRY_PASSWORD }} | docker login yny.ocir.io -u ${{ secrets.OCI_REGISTRY_USERNAME }} --password-stdin

    - name: Delete existing latest image
      run: |
        COMPARTMENT_ID="${{ secrets.OCI_COMPARTMENT_ID }}"
        REPOSITORY_NAME="adg"
        IMAGE_TAG="latest"
        IMAGE_OCID=$(oci artifacts container image list \
            --compartment-id $COMPARTMENT_ID \
            --repository-name $REPOSITORY_NAME \
            --output json | jq -r --arg tag "$IMAGE_TAG" '.data.items[] | select(.tags | index($tag)) | .id')
        if [ -n "$IMAGE_OCID" ]; then
            oci artifacts container image delete --image-id "$IMAGE_OCID" --force
        fi

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t yny.ocir.io/ax0ijnvub7pp/adg:${{ env.GIT_SHA }} -t yny.ocir.io/ax0ijnvub7pp/adg:latest --push .

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo ${{ secrets.OCI_REGISTRY_PASSWORD }} | docker login yny.ocir.io -u ${{ secrets.OCI_REGISTRY_USERNAME }} --password-stdin

          if [ "$(sudo docker ps -q -f name=adg)" ]; then
            sudo docker stop adg
            sudo docker rm adg
          fi

          sudo docker pull yny.ocir.io/ax0ijnvub7pp/adg:latest
          sudo docker run -d --name adg -p 8080:8080 yny.ocir.io/ax0ijnvub7pp/adg:latest
